--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Frago9876543210/ExamplePlugin
branches:
  - master
projects:
  ExamplePlugin:
    path: ""
    libs:
      - src: Frago9876543210/forms/libFormAPI
...